kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    hospital: hospital-1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      taints:
      - key: hospital
        value: hospital-1
        effect: NoExecute
- role: worker
  labels:
    hospital: hospital-2
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      taints:
      - key: hospital
        value: hospital-2
        effect: NoExecute