kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.Release.Name}}-config
  namespace: {{.Release.Namespace}}
data:
    # Add your configuration data here
    # For example:
    # database_url: "postgres://user:password@hostname:5432/dbname"
    LOG_LEVEL: {{.Values.config.LOG_LEVEL}}
    TENANT_NAME: {{.Values.config.TENANT_NAME}}
  


